import re
import hashlib
import logging
import unicodedata

from pathlib import Path


logger = logging.getLogger(__name__)


def sanitize_filename(text: str) -> str:
    """Cleans a string to create a safe, single-word filename.

    This function processes a string by performing several normalization and
    cleaning steps to make it suitable for use in filenames without spaces or
    special characters.

    The sanitization process includes:
    1.  Normalizing Unicode characters to their ASCII equivalents (e.g., 'ç' -> 'c').
    2.  Converting the string to lowercase.
    3.  Removing any character that is not a letter, number, whitespace, or hyphen.
    4.  Collapsing all spaces and hyphens, joining the string into a single word.

    Args:
        text (str): The original string to be sanitized.

    Returns:
        str: A clean, single-word string safe for use in filenames.
    """
    text = str(text)
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("utf-8")
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s-]+", "", text)

    return text


def generate_id(data: str) -> str:
    """Generates a deterministic SHA-256 hash from an input string.

    This utility function creates a unique and consistent identifier by hashing
    the provided string data. It is primarily used to generate stable IDs for
    entities like seasons, teams, and games from their string representations.

    Args:
        data (str): The input string to be hashed, such as a filename or a
            concatenation of identifiers.

    Returns:
        str: The resulting SHA-256 hash as a lowercase hexadecimal string.
    """
    return hashlib.sha256(data.encode("utf-8")).hexdigest()


def extract_metadata_from_filename(file_path: Path) -> dict:
    """Extracts structured metadata from a standardized filename.

    This function parses the stem of a filename to extract key information based
    on predefined patterns. It is designed to work with the output files
    generated by the scraper.

    The function supports two filename patterns:
    1.  Standings files: `{league_slug}_{season_year}_standings.csv`
    2.  Team game files: `{league_slug}_{season_year}_{team_name}.csv`

    Args:
        file_path (Path): The `pathlib.Path` object pointing to the file.

    Returns:
        dict: A dictionary containing the extracted metadata. Common keys include
            'type', 'league_name', and 'season_year'. For team game files, it
            also includes 'team_sanitized_name'.

    Raises:
        ValueError: If the filename does not match any of the expected patterns.
    """
    filename = file_path.stem
    logger.debug("Extracting metadata from filename: %s", filename)

    standings_match = re.match(r"([a-z0-9-]+)_(\d{4})_standings", filename)
    if standings_match:
        metadata = {
            "type": "standings",
            "league_name": standings_match.group(1),
            "season_year": int(standings_match.group(2)),
        }
        logger.debug("Matched standings file pattern: %s", metadata)
        return metadata

    games_match = re.match(r"([a-z0-9-]+)_(\d{4})_([a-z0-9-]+)", filename)
    if games_match:
        metadata = {
            "type": "games",
            "league_name": games_match.group(1),
            "season_year": int(games_match.group(2)),
            "team_sanitized_name": games_match.group(3),
        }
        logger.debug("Matched team games file pattern: %s", metadata)
        return metadata

    logger.error("Filename pattern not recognized for: %s", file_path)
    raise ValueError(f"Filename does not match expected patterns: {file_path}")


def validate_url_year(url: str, season_year: int) -> bool:
    """Validates if the year in a URL is consistent with the expected season year.

    This function checks for a `saison_id/YYYY` pattern within the given URL
    and compares the extracted year (`YYYY`) with the `season_year` from the
    file's metadata. The validation passes if the URL's year is less than or
    equal to the season year, which helps filter out incorrect URLs that might
    point to a future or different season's data.

    Args:
        url (str): The team URL string to be inspected.
        season_year (int): The season year derived from file metadata, used as
            the ground truth.

    Returns:
        bool: True if the URL is a valid string and its embedded year is less
            than or equal to the season year. Returns False otherwise.
    """
    if not isinstance(url, str):
        logger.warning("Invalid URL input: not a string. Received: %s", type(url))
        return False

    url_year_match = re.search(r"saison_id/(\d{4})", url)
    if not url_year_match:
        logger.warning("Year pattern 'saison_id/YYYY' not found in URL: %s", url)
        return False

    url_year = int(url_year_match.group(1))
    is_valid = url_year <= season_year
    if not is_valid:
        logger.warning(
            "URL year validation failed. URL year %d > Season year %d for URL: %s",
            url_year,
            season_year,
            url,
        )
    return is_valid
