from pathlib import Path

"""Centralizes all file system paths used throughout the project.

This module defines the complete directory structure for the application, from
the project root to specific data artifacts. Using this centralized module
prevents hardcoded paths, making the codebase more maintainable and portable.

The structure is organized into logical sections:
1.  Base Project Directory
2.  Core Application Directories (Logs, Data, Assets)
3.  Data Layer Directories (Bronze, Silver, Gold)
4.  Specific paths for assets, logs, and data artifacts within each layer.
5.  A function to initialize the entire directory structure on startup.
"""


# --- 1. Base Project Directory ---
ROOT_DIR = Path(__file__).resolve().parent.parent.parent

# --- 2. Core Application Directories ---
LOG_DIR = ROOT_DIR / "logs"
DATA_DIR = ROOT_DIR / "data"
ASSETS_DIR = ROOT_DIR / "assets"

# --- 3. Data Layer Directories ---

# Raw, unmodified data from the scraper.
BRONZE_DATA_DIR = DATA_DIR / "bronze"

# Processed, cleaned, and validated data.
SILVER_DATA_DIR = DATA_DIR / "silver"

# Analysis-ready data, models, and final artifacts (plots, reports).
GOLD_DATA_DIR = DATA_DIR / "gold"

# --- 4. Asset Paths ---
# Manually maintained files, such as configuration or overrides.
MANUAL_NAME_MAPPING_PATH = ASSETS_DIR / "manual_name_mapping.csv"

# --- 5. Log File Path ---
LOG_FILE = LOG_DIR / "app.log"

# --- 6. Bronze Layer Paths (Scraper Output) ---
SCRAPER_OUTPUT_DIR = BRONZE_DATA_DIR / "scraper"

# --- 7. Silver Layer Paths (Processor Output) ---

# Intermediate datasets containing all data before validation.
STANDINGS_COMPLETE_PATH = SILVER_DATA_DIR / "final_standings_complete.csv"
GAMES_COMPLETE_PATH = SILVER_DATA_DIR / "team_games_complete.csv"

# Final datasets containing only data from high-quality, valid seasons.
STANDINGS_VALID_PATH = SILVER_DATA_DIR / "final_standings_valid.csv"
STANDINGS_VALID_MARKET_RANKING_PATH = (
    SILVER_DATA_DIR / "final_standings_valid_market_ranking.csv"
)
STANDINGS_VALID_RANKING_PATH = (
    SILVER_DATA_DIR / "final_standings_valid_market_ranking.csv"
)
GAMES_VALID_PATH = SILVER_DATA_DIR / "team_games_valid.csv"

# Data quality summary artifact generated by the processor.
SEASON_SUMMARY_PATH = SILVER_DATA_DIR / "seasons_summary.csv"

# --- 8. Gold Layer Paths (Analysis & Mapping Artifacts) ---

# Base directories for analysis outputs.

ANALYSIS_OUTPUT_DIR = GOLD_DATA_DIR / "analysis"
NAME_MAPPINGS_DIR = GOLD_DATA_DIR / "name_mappings"

MANN_WHITNEY_DIR = ANALYSIS_OUTPUT_DIR / "mann_whitney"
MANN_WHITNEY_SEASONS = MANN_WHITNEY_DIR / "seasons"
MANN_WHITNEY_ATTENDANCE = MANN_WHITNEY_DIR / "attendance"

MANN_WHITNEY_ATT_AUDIT_DIR = MANN_WHITNEY_ATTENDANCE / "audit"
MANN_WHITNEY_ATT_METRICS_DIR = MANN_WHITNEY_ATTENDANCE / "metrics"
MANN_WHITNEY_ATT_PLOTS_DIR = MANN_WHITNEY_ATTENDANCE / "plots"

MANN_WHITNEY_METRICS_DIR = MANN_WHITNEY_SEASONS / "metrics"
MANN_WHITNEY_PLOTS_DIR = MANN_WHITNEY_SEASONS / "plots"


# Spearman coefficient related paths.
SPEARMAN_COEFFICIENT_DIR = ANALYSIS_OUTPUT_DIR / "spearman_coefficient"
SPEARMAN_COEFFICIENT_PLOTS = SPEARMAN_COEFFICIENT_DIR / "plots"
SPEARMAN_COEFFICIENT_METRICS = SPEARMAN_COEFFICIENT_DIR / "metrics"
SPEARMAN_BALANCE_PATH = SPEARMAN_COEFFICIENT_METRICS / "strength_schedule_balance.csv"
SPEARMAN_BALANCE_RANKING_PATH = (
    SPEARMAN_COEFFICIENT_METRICS / "strength_schedule_balance_ranking.csv"
)
SPEARMAN_BALANCE_MARKET_PATH = (
    SPEARMAN_COEFFICIENT_METRICS / "strength_schedule_balance_market.csv"
)
SPEARMAN_SUMMARY_PATH = SPEARMAN_COEFFICIENT_METRICS / "strength_schedule_summary.csv"

CLIFFS_DELTA_DIR = ANALYSIS_OUTPUT_DIR / "cliffs_delta"
SIGNIFICANCY_ANALYSIS_DIR = ANALYSIS_OUTPUT_DIR / "significancy_analysis"
SIGNIFICANCY_ANALYSIS_MARKET_DIR = SIGNIFICANCY_ANALYSIS_DIR / "market-value-proxy"
SIGNIFICANCY_ANALYSIS_FINAL_RANKING_DIR = (
    SIGNIFICANCY_ANALYSIS_DIR / "final-ranking-proxy"
)

# Schedule data paths used for analysis.
SCHEDULES_DATA_DIR = SPEARMAN_COEFFICIENT_DIR / "schedules_data"
SCHEDULES_DATA_COMBINED_DIR = SCHEDULES_DATA_DIR / "combined"
SCHEDULES_DATA_INDIVIDUAL_DIR = SCHEDULES_DATA_DIR / "individual"
SCHEDULES_DATA_COMBINED_PATH = (
    SCHEDULES_DATA_COMBINED_DIR / "schedule_data_combined.json"
)

# Name mappings paths generated by the processor.
NAME_MAPPINGS_COMBINED_DIR = NAME_MAPPINGS_DIR / "combined"
NAME_MAPPINGS_INDIVIDUAL_DIR = NAME_MAPPINGS_DIR / "individual"
NAME_MAPPINGS_COMBINED_PATH = NAME_MAPPINGS_COMBINED_DIR / "name_mappings_combined.csv"

# Statistical tests output paths.
OVERALL_MANN_WHITNEY_PATH = (
    MANN_WHITNEY_METRICS_DIR / "per_season_mann_whitney_p_values_summary.csv"
)

PER_SEASON_MANN_WHITNEY_PATH = (
    MANN_WHITNEY_METRICS_DIR / "per_season_mann_whitney_p_values.csv"
)
OCCUPANCY_P_VALUES_PATH = (
    MANN_WHITNEY_ATT_METRICS_DIR / "per_season_mann_whitney_p_values.csv"
)


# --- 9. Directory Initialization ---

# A list of all directories that must exist for the application to run.
DIRECTORIES_TO_CREATE = [
    LOG_DIR,
    ASSETS_DIR,
    BRONZE_DATA_DIR,
    SILVER_DATA_DIR,
    GOLD_DATA_DIR,
    SCRAPER_OUTPUT_DIR,
    ANALYSIS_OUTPUT_DIR,
    NAME_MAPPINGS_COMBINED_DIR,
    NAME_MAPPINGS_INDIVIDUAL_DIR,
    SPEARMAN_COEFFICIENT_DIR,
    SCHEDULES_DATA_COMBINED_DIR,
    SCHEDULES_DATA_INDIVIDUAL_DIR,
    MANN_WHITNEY_SEASONS,
    MANN_WHITNEY_ATTENDANCE,
    MANN_WHITNEY_DIR,
    SPEARMAN_COEFFICIENT_PLOTS,
    SPEARMAN_COEFFICIENT_METRICS,
    CLIFFS_DELTA_DIR,
    SIGNIFICANCY_ANALYSIS_DIR,
    SIGNIFICANCY_ANALYSIS_MARKET_DIR,
    SIGNIFICANCY_ANALYSIS_FINAL_RANKING_DIR,
    MANN_WHITNEY_ATT_AUDIT_DIR,
]


def create_project_directories():
    """Creates all necessary project directories if they do not already exist.

    This function iterates through the `DIRECTORIES_TO_CREATE` list and
    creates each one. It is idempotent, meaning it can be run multiple times
    without causing errors, as it will not try to recreate existing directories.
    """
    for directory in DIRECTORIES_TO_CREATE:
        directory.mkdir(parents=True, exist_ok=True)


# Automatically create directories when this module is imported.
create_project_directories()
